[project]
name = "celery-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "celery>=5.5.1",
    "flower>=2.0.1",
    "redis>=5.2.1",
]
